kind: Service
apiVersion: v1
metadata:
  name: wp
  namespace: harry-project
  selfLink: /api/v1/namespaces/harry-project/services/wp
  uid: 9eb6807b-b6fa-4105-8e5d-ff53dba4842f
  resourceVersion: '1757839'
  labels:
    app: wp
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: wp
    deploymentconfig: wp
  clusterIP: 172.30.214.30
  type: ClusterIP
  sessionAffinity: None
